---
title: "Sleep_Data_Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(magrittr)
library(knitr)
library('tidyverse')
library('tidyr')
library("readr")
library('here')
library("dplyr")
library("ggplot2")
library('lubridate')
library("reshape2")

```


```{r}
#Prepare variables for the environment

sleep_daily_cleaned <- as.data.frame(read.csv("G:/Google data analyst/Course-8/case-study/archive/Fitabase Data 4.12.16-5.12.16/Cleaned_datasets/Sleep/sleep_daily_cleaned.csv"))

mean_sleep_daily <-
  sleep_daily_cleaned %>%
  group_by(Date = date(mdy_hms(SleepDay))) %>%
  summarise(avg_sleep_record = round(mean(TotalSleepRecords),digits = 2),
            avg_minutes_asleep = round(mean(TotalMinutesAsleep),digits = 2),
            avg_TimeInBed = round(mean(TotalTimeInBed),digits = 2))
```

Column {data-width=1000}
-----------------------------------------------------------------------

### The total time spent in bed and the time spent asleep in bed

```{r}
Asleep_inbed <- subset(mean_sleep_daily, select = c(Date,avg_minutes_asleep,avg_TimeInBed) )

Asleep_inbed_long <-
  melt(Asleep_inbed,id = "Date")

sleep_time <- ggplot(data = Asleep_inbed_long, aes(x = Date, y = value/60, color = variable)) + 
  geom_line() +
  scale_x_date(date_labels = "%m-%d") +
  ylab("Hours") +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
  theme(legend.position = "bottom") + 
  labs(title = "The total time spent in bed and the time spent asleep in bed",
       subtitle = "Average data per person from 2016 April 12th to 2016 May 12th")

sleep_time

```


Column {data-width=1000}
-----------------------------------------------------------------------

### Time spent in bed awake each day

```{r}
time_awake <- ggplot(data = Asleep_inbed, aes(y = (avg_TimeInBed - avg_minutes_asleep) , x = Date)) + geom_line(color = "blue") +
  scale_x_date(date_labels = "%m-%d") + 
  ylab("Time awake in bed/minutes") +
  labs(title = "Time spent in bed awake each day",
       subtitle = "Average time per person from 2016 Apr 12th to 2016 May 12th")

time_awake

```

Column {data-width=1000}
-----------------------------------------------------------------------

### The percentage of time alseep to time spent in bed

```{r}
Asleep_inbed_2 <- Asleep_inbed %>% mutate(sleep_quality = (avg_minutes_asleep/avg_TimeInBed)*100)

sleep_quality <- ggplot(data = Asleep_inbed_2, aes(x = Date, y = sleep_quality))+
  geom_line(color = "purple") +
  scale_x_date(date_labels = "%m-%d") +
  ylab("time asleep/time in bed (%)") +
  labs(title = "The percentage of time alseep to time spent in bed",
       subtitle = "Avergae data per person from 2016 April 12th to 2016 May 12th")

sleep_quality

```
